### ISSUE TITLE
We have some problems

### ISSUE THREAD

**Issue by rzaharia** [diavolul999/Ip-Project#9]
We already have a main...
![image](https://cloud.githubusercontent.com/assets/13353201/21744792/942671fa-d525-11e6-9df8-7e99252e69d9.png)
You can also see so many error when i try to compile... Don't just commit something when it can't be compiled, please.

**Comment by alex-bucevschi** [comment]
I do not understand why this would depend on me

**Comment by rzaharia** [comment]
You can write a function which can pe called in main... Well..I don't know why this should depend on me either
